### PR TITLE
Start giving `cargo fix` a dedicated CLI

### LINKED ISSUE #70: Future-proof `cargo fix` CLI flags with Cargo's
Right now we blindly forward all arguments to `cargo fix` down to `cargo check`, which means that it may be difficult for us to add arguments to `cargo fix` itself. We'll want a story for how to add arguments to `cargo fix` specifically and how to specifically add arguments to the underlying Cargo subcommand.

### LINKED ISSUE #71: Support `cargo fix --help`
Right now I think this just executes `cargo check --help` which probably isn't too useful

### LINKED ISSUE #84: Add CLI flag to not revert broken changes
cf. <https://github.com/rust-lang-nursery/rustfix/pull/82#discussion_r186258642>

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit pulls in `clap` to have a location to actually insert a CLI for
`cargo fix` itself. This'll hopefully allow us to continue to configure
cargo-fix's behavior while also allowing passing arguments down to Cargo.

This starts out by adding a `--broken-code` option which can be used to specify
that previously broken code should be fixed, despite it being originally
broken.

Closes #70
Closes #71
Closes #84

### CODE REVIEW

**Comment by alexcrichton** [comment]
FWIW this is the first time I've ever written a clap app from scratch, so some extra scrutiny around that would be appreciated!

File: cargo-fix/tests/all/subtargets.rs [hunk 1]
```diff
@@ -28,7 +28,7 @@ fn fixes_missing_ampersand() {
 [COMPILING] foo v0.1.0 (CWD)
 [FINISHED] dev [unoptimized + debuginfo]
 ";
-    p.expect_cmd("cargo fix --all-targets").stdout("").stderr(stderr).run();
+    p.expect_cmd("cargo fix -- --all-targets").stdout("").stderr(stderr).run();
```
Comment (killercup) [inline cargo-fix/tests/all/subtargets.rs]: Hm, do you want to strictly separate which args are "cargo args" like `--all-targets` or `--features`, or do you eventually want to add args to cargo-fix that map to cargo args?

File: cargo-fix/src/main.rs [hunk 2]
```diff
@@ -163,7 +129,7 @@ fn rustfix_crate(rustc: &Path, filename: &str) -> Result<HashMap<String, String>
     //
     // TODO: this should be configurable by the CLI to sometimes proceed to
     // attempt to fix broken code.
-    if !output.status.success() {
+    if !output.status.success() && env::var_os("__CARGO_FIX_BROKEN_CODE").is_none() {
```
Comment (killercup) [inline cargo-fix/src/main.rs]: I fear that we'll be using a truckload of env vars soon (but it's not painful enough yet to fix)

File: cargo-fix/src/cli.rs [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+                .about("Automatically apply rustc's suggestions about fixing code")
+                .setting(AppSettings::TrailingVarArg)
+                .arg(Arg::with_name("args").multiple(true))
+                .arg(
+                    Arg::with_name("broken-code")
+                        .long("broken-code")
+                        .help("Fix code even if it already has compiler errors")
+                )
+        )
+        .get_matches();
```
Comment (killercup) [inline cargo-fix/src/cli.rs]: Looks good. I tend use structopt myself as it makes matching on subcommands and parsing args to types so much easier, but it's not a big deal here
